name: xwendngakan_app
description: "edu book - پلاتفۆرمی پەروەردەیی مۆدێرن"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  # State Management
  provider: ^6.1.2

  # Navigation
  go_router: ^13.2.1

  # HTTP & Networking
  http: ^1.2.0

  # Storage
  shared_preferences: ^2.2.3

  # UI
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  smooth_page_indicator: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  gap: ^3.0.1
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.7
  percent_indicator: ^4.2.3

  # Utils
  url_launcher: ^6.2.6
  share_plus: ^12.0.2
  connectivity_plus: ^6.0.3
  youtube_player_flutter: ^9.1.1

  # Maps
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  table_calendar: ^3.2.0
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  package_info_plus: ^9.0.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Rabar
      fonts:
        - asset: assets/fonts/Rabar-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rabar-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rabar-Bold.ttf
          weight: 700
